---
title: "Fantasy projections"
author: "Kynan Desouza-Chen"
date: "2023-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, message=FALSE, warning=FALSE}
library(dplyr)
library(rvest)
library(stringr)
library(tidyr)
```

```{r load-data}
hitter_dat <- read_html("https://www.fangraphs.com/projections?pos=all&stats=bat&type=rfangraphsdc&statgroup=fantasy") %>% html_elements('#__NEXT_DATA__') %>% html_text() %>% jsonlite::fromJSON()

hitter_data <- hitter_dat$props$pageProps$dehydratedState$queries$state$data[[1]]

positions_1 <- 
  read_html('https://www.espn.com/fantasy/baseball/story/_/id/35438162/fantasy-baseball-rankings-head-head-rotisserie-leagues-2023-espn-karabell') %>%
  html_table()

positions_2 <- read_html('https://www.espn.com/fantasy/baseball/story/_/id/35437997/fantasy-baseball-rankings-points-leagues-2023-espn-cockcroft') %>%
  html_table()

pitcher_dat <- read_html("https://www.fangraphs.com/projections?pos=&stats=pit&type=rfangraphsdc&statgroup=fantasy") %>% html_elements('#__NEXT_DATA__') %>% html_text() %>% jsonlite::fromJSON()

pitcher_data <- pitcher_dat$props$pageProps$dehydratedState$queries$state$data[[1]]
```

```{r clean-data}
clean_hitter_data <- hitter_data %>%
  select(
    PlayerName, Team, H, `1B`, `2B`, `3B`, HR, R, RBI, BB, SO, SB
    ) %>%
  mutate(PlayerName = janitor::make_clean_names(PlayerName, case = 'none'))

clean_pitcher_data <- pitcher_data %>%
  select(
    PlayerName, Team, IP, H, ER, BB, SO, W, L, SV, HLD
  )

clean_positions_1 <- positions_1 %>% 
  .[[1]] %>%
  select(Player, Team, `Elig. Pos.`) %>%
  mutate(
    Player = janitor::make_clean_names(Player, case = 'none'),
    Team = str_replace_all(Team, 'SD', 'SDP'),
    Team = str_replace_all(Team, 'TB', 'TBR'),
    Team = str_replace_all(Team, 'CWS', 'CHW'),
    Team = str_replace_all(Team, 'KC', 'KCR'),
    Team = str_replace_all(Team, 'SF', 'SFG'),
    Team = str_replace_all(Team, 'WSH', 'WSN'))

clean_positions_2 <- positions_2 %>%
  .[[1]] %>%
  select(Player, Team, `Elig. Pos.`) %>%
  mutate(
    Player = janitor::make_clean_names(Player, case = 'none'),
    Team = str_replace_all(Team, 'SD', 'SDP'),
    Team = str_replace_all(Team, 'TB', 'TBR'),
    Team = str_replace_all(Team, 'CWS', 'CHW'),
    Team = str_replace_all(Team, 'KC', 'KCR'),
    Team = str_replace_all(Team, 'SF', 'SFG'),
    Team = str_replace_all(Team, 'WSH', 'WSN'))

final_positions <- clean_positions_1 %>%
  full_join(clean_positions_2) %>%
  filter(!(str_detect(`Elig. Pos.`, 'P') & Player != 'Shohei_Ohtani'))
```

```{r add-eligible-positions}
final_hitter_data <- clean_hitter_data %>% 
  right_join(final_positions, by = c('PlayerName'='Player', 'Team'='Team'))
```


```{r projected-pts}
compute_batter_points <- function(R, TB, RBI, BB, K, SB) {
  R + TB + RBI + BB - K + SB
}

compute_pitcher_points <- function(IP, H, ER, BB, K, W, L, SV, HD) {
  3*IP - H - 2*ER - BB + K + 2*W - 2*L + 5*SV + 2*HD
}

final_hitter_data %>% 
  mutate(
    TB = `1B` + 2*`2B` + 3*`3B` + 4*HR,
    Points = compute_batter_points(R, TB, RBI, BB, SO, SB)) %>%
  filter(str_detect(`Elig. Pos.`, '3')) %>%
  select(PlayerName, Team, `Elig. Pos.`,Points) %>%
  arrange(desc(Points))

clean_pitcher_data %>%
  mutate(Points = compute_pitcher_points(IP, H, ER, BB, SO, W, L, SV, HLD)) %>%
  select(PlayerName, Team, Points) %>%
  arrange(desc(Points))
```