---
title: "Test Scraping"
author: "Kynan Desouza-Chen"
date: "2023-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, message=FALSE, warning=FALSE}
library(dplyr)
library(janitor)
library(rvest)
```

```{r load-data, message=FALSE}
page <- read_html("https://www.fangraphs.com/leaders.aspx?pos=all&stats=bat&lg=nl&qual=y&type=c,4,6,7,9,10,11,14,16,21,289,290,291,292,61,53,111,203,54,56,199,204,55,57,58&season=2022&month=0&season1=1871&ind=1&team=0&rost=&age=&filter=&players=&startdate=&enddate=&page=1_10000")
```

```{r extract-table}
leaderboardNL <- page %>% 
  html_nodes("table") %>%
  .[[7]] %>%
  html_table()
```

```{r clean-table}
cleanLeaderboardNL <- leaderboardNL %>%
  filter(!row_number() %in% c(1, 3)) %>%
  row_to_names(row_number = 1) %>%
  select(-c(`#`, Team)) %>%
  mutate(Season = factor(Season))

convertToDouble <- sapply(cleanLeaderboardNL[ , -c(2)], as.double)

colnames <- colnames(cleanLeaderboardNL)
cleanLeaderboardNL[ , colnames %in% colnames(convertToDouble)] <- convertToDouble

head(cleanLeaderboardNL)
```

```{r augment-leaderboard}
augmentedLeaderboardNL <- cleanLeaderboardNL %>%
  filter(WAR > 0) %>%
  mutate(individualRPW = RAR/WAR) %>%
  group_by(Season) %>%
  mutate(
    RPW = mean(individualRPW), 
    WAA = round((RAR - Rep)/RPW, digits = 1)) %>%
  select(-c(individualRPW, RPW)) %>%
  filter(WAA > 0) %>%
  arrange(desc(WAA))
```

```{r show-candidates}
candidates <- augmentedLeaderboardNL %>%
  group_by(Season) %>%
  mutate(threshold = round(max(WAA)*0.85, digits = 1) - 0.1) %>%
  filter(WAA >= threshold) %>%
  select(-c(threshold)) %>%
  arrange(desc(Season))
```




